name: "Feature"
description: "New feature or request"
title: "[FEAT] "
labels: ["feature"]
body:
 
  - type: textarea
    id: what-needs-to-be-done
    attributes:
      label: "Was muss getan werden?"
      value: "- [ ] "
    validations:
      required: true

  - type: textarea
    id: blocked-by
    attributes:
      label: "Blockiert durch:"
      value: "- #"
    validations:
      required: false
 
  - type: dropdown
    id: version
    attributes:
      label: "Priorität:"
      description: Wie wichtig ist das Feature?
      options:
        - Optional / Nice to have
        - Könnte zur Not warten
        - So schnell es geht
      default: 1
    validations:
      required: true
 
  - type: textarea
    id: comment
    attributes:
      label: "Kommentar"
    validations:
      required: false
 
